import re
from typing import Annotated, Final

from pydantic import field_validator, model_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

from code_review.models.config import ReviewConfig, ReviewModel
from code_review.models.severity import Severity

DISCLAIMER: Final[str] = (
    "_This response was AI generated by "
    "[code-review-action](https://github.com/julien777z/code-review-action)._"
)


CONFIG: Final[ReviewConfig] = ReviewConfig(
    review_marker="<!-- code-review -->",
    no_findings_marker="NO_FINDINGS",
    untrusted_input_open="<!-- UNTRUSTED_INPUT START -->",
    untrusted_input_close="<!-- UNTRUSTED_INPUT END -->",
    summary_marker_open="<!-- code-review:summary:start -->",
    summary_marker_close="<!-- code-review:summary:end -->",
    status_check_name="Approval Verdict",
    default_claude_model="claude-opus-4-8",
    default_cursor_model="composer-2.5",
)


def split_list(value: str) -> tuple[str, ...]:
    """Split a comma/newline-separated input into a tuple of non-empty items."""

    return tuple(part.strip() for part in re.split(r"[,\n]", value) if part.strip())


def parse_bool(value: str) -> bool:
    """Parse a boolean action input."""

    return value.strip().lower() in ("1", "true", "yes", "on")


class Settings(BaseSettings):
    """Runtime configuration assembled from the action inputs (environment)."""

    model_config = SettingsConfigDict(case_sensitive=False, extra="ignore")

    github_token: str = ""
    resolve_token: str = ""
    anthropic_api_key: str = ""
    cursor_api_key: str = ""
    review_model: ReviewModel = ReviewModel.AUTO
    first_review_model: ReviewModel | None = None
    claude_model: str = CONFIG["default_claude_model"]
    cursor_model: str = CONFIG["default_cursor_model"]
    additional_context: str = ""
    approval_include: Annotated[frozenset[Severity], NoDecode] = frozenset({Severity.CRITICAL})
    approval_disable: bool = False
    pr_review_summary: bool = True
    enforce_project_rules: bool = True
    project_rules_severity: Severity | None = None
    simplify_suggest: bool = False
    simplify_suggest_severity: Severity | None = None
    simplify_nearby_code: bool = False
    min_severity: Severity = Severity.LOW
    low_findings_cap: int = 3
    max_findings: int | None = None
    include_paths: Annotated[tuple[str, ...], NoDecode] = ()
    exclude_paths: Annotated[tuple[str, ...], NoDecode] = ()
    trigger_phrase: str = "agent review"
    review_drafts: bool = True
    author_associations: Annotated[tuple[str, ...], NoDecode] = ()
    pr_number: int | None = None

    @model_validator(mode="before")
    @classmethod
    def strip_blank_inputs(cls, data: dict[str, str]) -> dict[str, str]:
        """Strip whitespace from inputs and drop blanks so field defaults apply."""

        return {key: stripped for key, value in data.items() if (stripped := value.strip())}

    @field_validator(
        "review_model",
        "first_review_model",
        "min_severity",
        "project_rules_severity",
        "simplify_suggest_severity",
        mode="before",
    )
    @classmethod
    def normalize_enum(cls, value: str | None) -> str | None:
        """Trim and lower-case an enum input so it matches the enum's values."""

        return value.strip().lower() if value is not None else value

    @field_validator(
        "approval_disable",
        "review_drafts",
        "pr_review_summary",
        "enforce_project_rules",
        "simplify_suggest",
        "simplify_nearby_code",
        mode="before",
    )
    @classmethod
    def normalize_bool(cls, value: str | bool) -> bool:
        """Parse a boolean input from its string form."""

        return parse_bool(value) if isinstance(value, str) else value

    @field_validator("approval_include", mode="before")
    @classmethod
    def normalize_severities(cls, value: str | frozenset[Severity]) -> frozenset[Severity]:
        """Parse a comma-separated severity list, defaulting to critical when empty."""

        if not isinstance(value, str):
            return value

        return frozenset(Severity.from_str(item) for item in split_list(value)) or frozenset({Severity.CRITICAL})

    @field_validator("include_paths", "exclude_paths", mode="before")
    @classmethod
    def normalize_paths(cls, value: str | tuple[str, ...]) -> tuple[str, ...]:
        """Split a comma/newline glob list into a tuple."""

        return split_list(value) if isinstance(value, str) else value

    @field_validator("author_associations", mode="before")
    @classmethod
    def normalize_associations(cls, value: str | tuple[str, ...]) -> tuple[str, ...]:
        """Split and upper-case the author-association allowlist."""

        return tuple(item.upper() for item in split_list(value)) if isinstance(value, str) else value


SETTINGS: Final[Settings] = Settings()
